#########################################
### Hashtopolis Submit hash settings. ###
#########################################
# Enabled the Pwn2Crack plugin
main.plugins.pwn2crack.enabled = true

# Required: The web URL(IP or Domian name) to the Hashtopolis server.
main.plugins.pwn2crack.htserver = "http://10.100.200.250"

# Required: The API key you get from the Hashtopolis server
# To get a Hashtopolis API key, log into your Hashtopolis server and go to "Users" --> "API Management" --> "Create New API Key".
main.plugins.pwn2crack.accesskey = "MyKey"

# Optional: Is the Hash secret? If not set Pwn2Crack defaults to "true"
main.plugins.pwn2crack.hashisSecret = true

# Optional: Are you using a Hashcat Brain Server?
# If you enable this, you must have it enabled in the Hashtopolis server, else the hash uploads will fail.
main.plugins.pwn2crack.useBrain = false
main.plugins.pwn2crack.brainFeatures = 0

# Optional: Creat a wordlist from the ESSID data? Good for target specific wordlist. If not specified, then false.
main.plugins.pwn2crack.genwordlist = false
# Uplaod the list to the Hashtopolist sever as a wordlist file?
main.plugins.pwn2crack.uploadwordlist = false

# Optional: Limit the number of hashes per AP uploaded to Hashtopolis. One AP can have many clients.
#            The same AP, same password, will have a unqiue hash per client. If you upload five unqiue
#            hashes for one AP, Hashcat will have to do the hash calculations five times, for the same
#            one password guess. This is inefficient, and will slowdown cracking times. However, hashes
#            can be corrupt, for many different reasons. So you may want two to three hashes per AP
#            encase one is bad.
#            If not set, the default is to upload all hashes. Setting this to '0' will also upload all hashes.
main.plugins.pwn2crack.numhashtoupload = 0
#########################################